package leetcode.easy;

public class FindDifference {
    //problem:
    //You are given two strings s and t.
    //String t is generated by random shuffling string s and then add one more letter at a random position.
    //Return the letter that was added to t.
    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd", "aecdb"));//output: e
    }

    public static char findTheDifference(String s, String t) {
        int freq[] = new int[26];
        int len = s.length();

        char sChars[] = s.toCharArray();
        char tChars[] = t.toCharArray();

        for (int i = 0; i < len; i++){
            freq[sChars[i] - 'a']++;
            freq[tChars[i] - 'a']--;
        }

        freq[tChars[len] - 'a']--;

        for (int i = 0; i < 26; i++){
            if (freq[i] == -1){
                return (char) (i + 'a');
            }
        }

        return ' ';
    }
}
